
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpxylitfeoyekqjwxdwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRweHlsaXRmZW95ZWtxand4ZHd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzE2MjEsImV4cCI6MjA1OTYwNzYyMX0.2AZwY1WbnTl80LgfAAk1YzMLi1MpU5Aq7kdNZd3A53o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
